# Generated by Django 3.2.9 on 2021-11-18 14:40

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_rename_user_ticket_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=pathlib.PureWindowsPath('C:/Users/benoi/Documents/GitHub/projet_09/LITReview/media')),
        ),
    ]
