# Generated by Django 3.2.9 on 2021-12-02 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_alter_ticket_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='has_review',
        ),
    ]
